### PR TITLE
fix(collapsible panel): adds pointer when cursor is hovered over icon

### LINKED ISSUE #182: Collapsible Panel missing hover pointer
## 🐛 Bug Report

When hovering a the button that collapses the panel the default pointer is uses instead of index finger.

## To Reproduce
Test it on https://components.hospitalrun.io/?path=/story/panel--collapsed-collapsible-panel

## Expected behavior

When hovering the button index finger is used instead of default ones.
## Your Environment
- *os*: MacOS Catalina
- *browser*: latest Firefox and Chrome

### PR DESCRIPTION
**Pull request by alexpatow**
adds pointer when cursor is hovered over collapse/expand icon on the collapsible panel

fix #182

Fixes #182.

**Changes proposed in this pull request:**
- Adds cursor CSS
- Label.tsx was changed by linting on commit

### CODE REVIEW

**Comment by jackcmeyer** [comment]
Hey @alexpatow! Welcome to the HospitalRun community and thanks for your first contribution! Please make sure to sign our [Contributor License Agreement](https://cla.js.foundation/HospitalRun/components?pullRequest=184) so that we can mere your Pull Request!

**Comment by alexpatow** [comment]
Hey, I’ve signed it!

**Comment by jackcmeyer** [comment]
@alexpatow hmmm maybe the bot is acting up. Could you try one more time (needs to be with the account that you opened up the PR with)

**Comment by fox1t** [comment]
Well done @alexpatow. I think that @jackcmeyer find the problem You have 2 different accounts and the one that made the commit didn't singed the CLA. Can you fix it, so we can merge?

**Comment by fox1t** [comment]
LGTM

**Comment by tehKapa** [comment]
Hi @alexpatow, could you sign with the same id that you used to commit here on GH? as you can see, the PR isn't still signed correctly. https://github.com/HospitalRun/components/pull/184#issuecomment-570392705   

thank you!

**Comment by alex-patow** [comment]
Should be good to go now, sorry about that

**Comment by fox1t** [comment]
No worries!

**Pull request merged**
