### PR TITLE
feat(select): Filterable select component

### LINKED ISSUE #322: Create a filterable select component
## 🚀 Feature Proposal

To create a filterable select component, useful in table filters and forms.

## Motivation

Table text columns with lots of data need a faster way to filter results.
Options for the component need to be passed from outside.

## Example

Something like this --> [https://semantic-ui.com/modules/dropdown.html#search-selection](https://semantic-ui.com/modules/dropdown.html#search-selection)

### PR DESCRIPTION
**Pull request by kumikokashii**
Fixes #322.

**Changes proposed in this pull request:**
- Select component uses React Bootstrap Typeahead, like [this](http://ericgio.github.io/react-bootstrap-typeahead/). [Navbar](https://github.com/HospitalRun/components/blob/master/src/components/Navbar/Navbar.tsx) also uses Typehead.

**Please read:**
- With the updated Select component, frontend will require an update. Specifically, all instances of SelectWithLabelFormGroup will need to be replaced with Label and Select.
- When the `multiple` prop is set to `true`, the input box's border color is blue instead of green.

### CODE REVIEW

**Comment by tehKapa** [comment]
lint and fix

**Comment by tehKapa** [comment]
GitHub please lint and fix this PR

**Comment by tehKapa** [comment]
GitHub please lint and fix this PR

**Comment by tehKapa** [comment]
GitHub please lint and fix this PR

**Comment by fox1t** [comment]
@jackcmeyer is it ok to use alerts on our stoybooks? What is the usual pattern to notify users about interactions?

**Comment by jackcmeyer** [comment]
> @jackcmeyer is it ok to use alerts on our stoybooks? What is the usual pattern to notify users about interactions?

This is fine in storybook!

**Pull request merged**
