### PR TITLE
feat(checkboxes): adds Checkbox component

### LINKED ISSUE #62: Checkbox
## 🚀 Feature Proposal

Add checkbox to the component library.

## Motivation

Check boxes are an important part of forms. 

## Example

Whether or not a patient has a certain characteristic that is either true or false.

https://react-bootstrap.netlify.com/components/forms/#forms-form-check

## Related
#32

### PR DESCRIPTION
**Pull request by jackcmeyer**
Fixes #62

**Changes proposed in this pull request:**
- Adds Checkbox component

### CODE REVIEW

**Comment by fox1t** [comment]
LGTM

**Comment by tehKapa** [comment]
@jackcmeyer, can you also make the text label clickable?

**Comment by jackcmeyer** [comment]
> @jackcmeyer, can you also make the text label clickable?

@tehKapa I can try 😀

**Comment by jackcmeyer** [comment]
@tehKapa ability to click on the label has been added

**Comment by irvelervel** [comment]
Nice work @jackcmeyer !

**Pull request merged**
