### PR TITLE
refactor(linter): Add linter rules for import order

### PR DESCRIPTION
**Pull request by MatthewDorner**
**Changes proposed in this pull request:**
- Add `import/order` rule, same as https://github.com/HospitalRun/hospitalrun-frontend/pull/2074.

### CODE REVIEW

**Comment by MatthewDorner** [comment]
Any other repositories to do this for?

**Comment by fox1t** [comment]
@MatthewDorner core and server need your care too! :)

**Comment by fox1t** [comment]
@jackcmeyer or @tehKapa Any clues why windows is not building? O_o

**Comment by tehKapa** [comment]
> @jackcmeyer or @tehKapa Any clues why windows is not building? O_o

There seems to be a nonsens TS error, for friend "[semantic error TS2769: No overload matches this call](https://github.com/HospitalRun/components/pull/423/checks?check_run_id=688067761#step:8:16)"

**Comment by jackcmeyer** [comment]
> > @jackcmeyer or @tehKapa Any clues why windows is not building? O_o
> 
> @fox1t there seems to be a nonsens TS error, for friend "[semantic error TS2769: No overload matches this call](https://github.com/HospitalRun/components/pull/423/checks?check_run_id=688067761#step:8:16)"
> 
> Can we merge this PR and solve the other issue in a new PR?

IMO, we should merge it.

**Pull request merged**
